---
apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail
data:
  promtail.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0

    positions:
      filename: /run/promtail/positions.yaml

    clients:
      - url: 'http://loki:3100/loki/api/v1/push'

    scrape_configs:
      - job_name: system
        static_configs:
          - labels:
              job: varlogs
              host: k8s-node
              __path__: /var/log/*.log
      - job_name: kubernetes-pods
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - action: replace
            source_labels:
              - __meta_kubernetes_pod_label_app_kubernetes_io_name
            target_label: app


