---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vault
  namespace: vault
data:
  config.hcl: |
    storage "file" {
      path = "/vault/file/"
    }

    ui = true
    api_addr = "http://127.0.0.1:8200"
    cluster_addr = "http://127.0.0.1:8201"

    listener "tcp" {
      address = "0.0.0.0:8200"
      cluster_address = "0.0.0.0:8201"
      tls_disable = true
    }

    log_level = "Info"
    log_format = "json"