---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: game-servers-pv
  namespace: game-servers
spec:
  storageClassName: manual
  capacity:
    storage: 32Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/k8s/games"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: game-servers-pvc
  namespace: game-servers
spec:
  storageClassName: manual
  resources:
    requests:
      storage: 32Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
