---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: valheim-server
  namespace: game-servers
spec:
  selector:
    matchLabels:
      app: valheim-server
  template:
    metadata:
      labels:
        app: valheim-server
    spec:
      containers:
        - image: lloesche/valheim-server:latest
          name: valheim-server
          env:
            - name: SERVER_NAME
              value: 'RC Test Server'
            - name: WORLD_NAME
              value: 'RC Test World'
            - name: SERVER_PASS
              value: 'snapje'
          ports:
            - containerPort: 2456
              name: valheim0
              protocol: UDP
            - containerPort: 2457
              name: valheim1
              protocol: UDP
            - containerPort: 2458
              name: valheim2
              protocol: UDP
          volumeMounts:
            - name: data
              mountPath: /data/valheim
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: game-servers-pvc