#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: valheim-server
#  namespace: game-servers
#  labels:
#    app: valheim-server
#spec:
#  ports:
#    - name: valheim0
#      port: 2456
#      targetPort: 2456
#      protocol: UDP
#    - name: valheim1
#      port: 2457
#      targetPort: 2457
#      protocol: UDP
#    - name: valheim2
#      port: 2458
#      targetPort: 2458
#      protocol: UDP
#  selector:
#    app: valheim-server

---
apiVersion: v1
kind: Service
metadata:
  name: valheim-server
  namespace: game-servers
  labels:
    app: valheim-server
  annotations:
    metallb.universe.tf/allow-shared-ip: "shared-ip"
spec:
  ports:
    - protocol: UDP
      name: valheim0
      port: 2456
    - protocol: UDP
      name: valheim1
      port: 2457
    - protocol: UDP
      name: valheim2
      port: 2458
  type: LoadBalancer
  selector:
    app: valheim-server