---
apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch
  namespace: elk
  labels:
    app.kubernetes.io/name: elk
    app.kubernetes.io/component: elasticsearch
    app.kubernetes.io/version: "7"
data:
  elasticsearch.yml: |
    discovery.type: single-node
    cluster.name: "k8s"
    network.host: 0.0.0.0
    xpack.security.enabled: true