---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: elasticsearch
  namespace: elk
  labels:
    app.kubernetes.io/name: elk
    app.kubernetes.io/component: elasticsearch
    app.kubernetes.io/version: "7"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: elasticsearch
  template:
    metadata:
      labels:
        app.kubernetes.io/name: elk
        app.kubernetes.io/component: elasticsearch
        app.kubernetes.io/version: "7"
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
          env:
            - name: discovery.type
              value: single-node
            - name: ES_JAVA_OPTS
              value: "-Xms512m -Xmx512m"
#            - name: ES_PATH_CONF
#              value: /etc/elasticsearch
          ports:
            - containerPort: 9200
              protocol: TCP
            - containerPort: 9300
              protocol: TCP
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: elk-data
            - mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
              subPath: elasticsearch.yml
              name: elk-config
            - mountPath: /usr/share/elasticsearch/config/elasticsearch.keystore
              subPath: elasticsearch.keystore
              name: elk-keystore
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
      securityContext:
        runAsNonRoot: true
        runAsGroup: 1000
        runAsUser: 1000
      volumes:
        - name: elk-data
          persistentVolumeClaim:
            claimName: elasticsearch-pvc
        - name: elk-config
          configMap:
            name: elasticsearch
        - name: elk-keystore
          secret:
            secretName: elasticsearch