---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: elk
  labels:
    app.kubernetes.io/name: elk
    app.kubernetes.io/component: elasticsearch
    app.kubernetes.io/version: "7"
spec:
  selector:
    app.kubernetes.io/name: elk
    app.kubernetes.io/component: elasticsearch
    app.kubernetes.io/version: "7"
  ports:
    - name: elk-9200
      port: 9200
      protocol: TCP
      targetPort: 9200
    - name: elk-9300
      protocol: TCP
      port: 9300
      targetPort: 9300