---
- name: Install MicroK8s
  snap:
    name: microk8s
    classic: true

- name: Wait for MicroK8s to be ready
  shell:
    cmd: microk8s status --wait-ready
  register: microk8s_status
  retries: 10
  wait_for: microk8s_status.rc == 0

- name: Show status
  debug:
    var: microk8s_status.stdout

- name: Configure port based UFW rules
  ufw:
    rule: allow
    port: "{{ item.port }}"
    protocol: "{{ item.protocol }}"
    comment: "{{ item.comment }}"
  loop:
    - { port: 16443, protocol:  tcp, comment: "microk8s kube-apiserver" }
    - { port: 10250, protocol: tcp, comment: "k8s kubelet" }
    - { port: 10253, protocol: tcp, comment: "k8s kube-proxy" }
    - { port: 10257, protocol: tcp, comment: "k8s kube-controller-manager" }
    - { port: 10259, protocol: tcp, comment: "k8s kube-scheduler" }
  register: ufw_rules

- name: Enable MicroK8s addons
  shell:
    cmd: "microk8s enable {{ addon }}"
  loop_control:
    loop_var: addon
  loop:
    - communtiy
    - dns
    - argocd
    - keda
    - hostpath-storage
    - metrics-server

- name: Add user to MicroK8s group
  user:
    name: "{{ username }}"
    append: true
    groups:
      - microk8s