apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-conf
  namespace: traefik
  labels:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/component: traefik
    app.kubernetes.io/version: "2"
data:
  traefik.yaml: |
    api:
      insecure: true
      dashboard: true
      
    ping: {}
      
    metrics:
      prometheus:
        addEntryPointsLabels: true
        addRoutersLabels: true
        addServicesLabels: true
        
    log:
      level: INFO
      filePath: "/var/log/traefik/app.log"
      format: json
    accessLog:
      filePath: "/var/log/traefik/access.log"
      format: json

    entryPoints:
      http:
        address: ':80'
        http:
          redirections:
            entryPoint:
              to: https
              scheme: https
              permanent: true
      https:
        address: ':443'
        http:
          tls: 
            certResolver: cr
        forwardedHeaders:
          insecure: true
            
    certificatesResolvers:
      cr:
        acme:
          email: "ralph@comanne.eu"
          storage: "/acme/data.json"
          tlsChallenge: {}
        
    providers:
      kubernetesIngress: {}
      kubernetesCRD: {}
      
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: beats
  namespace: traefik
  labels:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/component: beats
    app.kubernetes.io/version: "2"
data:
  filebeat.yml: |
    filebeat.inputs:
      - type: log
        paths:
          - /var/log/traefik/*.log
        json:
          keys_under_root: true
          overwrite_keys: true
          add_error_key: true
          
    processors:
      - add_fields:
          target: ''
          fields:
            app_name: traefik
            
      - timestamp:
          field: time
          layouts:
            - '2021-12-04T22:10:53Z'
            
      - drop_fields:
          fields:
            - time
            - msg
            
    setup:
      ilm:
        enabled: true
        rollover_alias: "traefik"
        policy_name: traefik
    
    output.elasticsearch:
      hosts: ["http://elasticsearch.elk.svc.cluster.local:9200"]
      username: "${ES_USER}"
      password: "${ES_PASS}"

  metricbeat.yml: |
    
