apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-conf
  namespace: traefik
data:
  traefik.toml: |
    [log]
      level = "DEBUG"
      filePath = "/var/log/traefik.log"
      format = "common"
    [accessLog]
      filePath = "/var/log/access.log"
      format = "common"

    [entryPoints]
      [entryPoints.http]
        address = ":80"
          [entryPoints.http.http.redirections.entryPoint]
            to = "https"
            scheme = "https"
      [entryPoints.https]
        address = ":443"
          [entryPoints.https.http.tls]

      [entryPoints.valheim0]
        address = ":2456/udp"
      [entryPoints.valheim1]
        address = ":2457/udp"
      [entryPoints.valheim2]
        address = ":2458/udp"

    [api]
      insecure = true
      dashboard = true

    [providers]
      [providers.kubernetesIngress]
        ingressClass = "traefik-external"

    [ping]
      entryPoint = "http"

    [certificatesResolvers]
      [certificatesResolvers.cr.acme]
        email = "ralph@comanne.eu"
        storage = "/acme/data.json"
        [certificatesResolvers.cr.acme.tlsChallenge]
