---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: traefik
  name: traefik
  labels:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/component: traefik
    app.kubernetes.io/version: 2
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: traefik
      app.kubernetes.io/component: traefik
  template:
    metadata:
      labels:
        app.kubernetes.io/name: traefik
        app.kubernetes.io/component: traefik
        app.kubernetes.io/version: 2
    spec:
      serviceAccountName: traefik
      containers:
        - name: traefik
          image: traefik:v2.4
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /etc/traefik
              name: config
            - mountPath: /acme
              name: acme
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
            - name: admin
              containerPort: 8080
      volumes:
        - name: config
          configMap:
            name: traefik-conf
        - name: acme
          persistentVolumeClaim:
            claimName: traefik-pvc