---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: docker-registry-pv
  namespace: docker
spec:
  storageClassName: manual
  capacity:
    storage: 32Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/k8s/docker"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-registry-pvc
  namespace: docker
spec:
  storageClassName: manual
  resources:
    requests:
      storage: 32Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
