apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: elastic-agent
  namespace: elk
  labels:
    app.kubernetes.io/name: elk
    app.kubernetes.io/component: elastic-agent
    app.kubernetes.io/version: "7"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: elk
      app.kubernetes.io/component: elastic-agent
      app.kubernetes.io/version: "7"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: elk
        app.kubernetes.io/component: elastic-agent
        app.kubernetes.io/version: "7"
    spec:
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      serviceAccountName: elastic-agent
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: elastic-agent
          image: docker.elastic.co/beats/elastic-agent:7.15.2
          args: [
              "-c", "/etc/agent.yml",
              "-e",
          ]
          env:
            - name: ES_USERNAME
              valueFrom:
                secretKeyRef:
                  key: elastic_username
                  name: elasticsearch
            - name: ES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: elastic_password
                  name: elasticsearch
            - name: ES_HOST
              value: "http://elasticsearch.elk.svc.cluster.local:9200"
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          securityContext:
            runAsUser: 0
          resources:
            limits:
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 200Mi
          volumeMounts:
            - name: datastreams
              mountPath: /etc/agent.yml
              readOnly: true
              subPath: agent.yml
            - name: proc
              mountPath: /hostfs/proc
              readOnly: true
            - name: cgroup
              mountPath: /hostfs/sys/fs/cgroup
              readOnly: true
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: varlog
              mountPath: /var/log
              readOnly: true
      volumes:
        - name: datastreams
          configMap:
            defaultMode: 0640
            name: agent-node-datastreams
        - name: proc
          hostPath:
            path: /proc
        - name: cgroup
          hostPath:
            path: /sys/fs/cgroup
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: varlog
          hostPath:
            path: /var/log