---
- name: Init k8s
  command:
    cmd: "kubeadm init --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address={{ ansible_facts['eth0']['ipv4']['address'] }}"
    creates: /etc/kubernetes/admin.conf

- name: Ensure root .kube dir exists
  file:
    path: "/root/.kube"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0700

- name: Copy admin config.yml to root home
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "/root/.kube/config.yml"
    owner: root
    group: root
    mode: 0600

- name: Copy admin config.yml to local
  copy:
    remote_src: true
    src: /etc/kubernetes/admin.conf
    dest: "/{{ local_user }}/.kube/config.yml"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0600