---
- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /etc/apt/trusted.gpg.d/docker.gpg
    state: present

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch=amd64 signedby=/etc/apt/trusted.gpg.d/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_facts['distribution_release'] }} stable"
    state: present
    update_cache: true

- name: Install containerd runtime
  apt:
    name:
      - docker-ci
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: latest