---
- name: Install Docker
  import_tasks: install_docker.yml
  become: yes

- name: Pre Kubernetes configuration
  import_tasks: pre_config.yml
  become: yes

- name: Kubernetes
  import_tasks: install.yml
  become: yes

- name: Initialize Kubernetes
  import_tasks: initialize.yml
  become: yes

- name: Post Kubernetes configuration
  import_tasks: post_config.yml

- name: Install & configure LoadBalancer
  import_tasks: loadbalancer.yml