---
- name: Add repository key
  apt_key:
    url: https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public
    state: present

- name: Add repository
  apt_repository:
    repo: "deb https://adoptopenjdk.jfrog.io/adoptopenjdk/deb {{ ansible_facts['distribution_release'] }} main"
    state: present
    update_cache: true

- name: Install AdoptOpenJDK 11
  apt:
    name: adoptopenjdk-11-hotspot
    state: latest