---
- set_fact:
    jenkins_resources_dir: "/tmp/jenkins"

- name: Create jenkins tmp dir
  file:
    path: "{{ jenkins_resources_dir }}"
    state: directory

- name: Copy Jenkins namespace.yml
  copy:
    src: 01-namespace.yml
    dest: "{{ jenkins_resources_dir }}/01-01-namespace.yml"

- name: Copy Jenkins deployment.yml
  copy:
    src: 02-deployment.yml
    dest: "{{ jenkins_resources_dir }}/02-jenkins_deployment.yml"

- name: Copy Jenkins service.yml
  copy:
    src: 03-service.yml
    dest: "{{ jenkins_resources_dir }}/03-jenkins_service.yml"

- name: Apply Jenkins configuration
  command:
    cmd: "kubectl apply -f {{ jenkins_resources_dir }}"