---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: loki
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
        - name: loki
          image: grafana/loki:2.2.1
          imagePullPolicy: Always
          ports:
            - name: web
              containerPort: 3100
          volumeMounts:
            - name: config
              mountPath: /etc/loki
            - name: data
              mountPath: /loki
          securityContext:
            runAsUser: 10001
            runAsGroup: 10001
            runAsNonRoot: true
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: loki-pvc
        - name: config
          configMap:
            name: loki