apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana
  namespace: elk
data:
  kibana.yml: |
    elasticsearch:
      hosts: ["http://elasticsearch.elk.svc.cluster.local:9200"]
      username: kibana_system
      
    
    server:
      host: 0.0.0.0