---
- name: Ensure commonly needed packages are installed and up to date
  apt:
    name:
      - software-properties-common
      - apt-transport-https
      - curl
      - wget
      - gnupg
      - fail2ban
      - zsh
      - git
      - net-tools
    state: latest

- name: Ensure hostname is set
  hostname:
    name: "{{ hostname }}"

- name: Ensure locale set
  template:
    src: locale.conf.j2
    dest: /etc/default/locale
  notify:
    - reboot system

- name: Configure port based UFW rules
  ufw:
    rule: allow
    port: "{{ item.port }}"
    protocol: "{{ item.protocol }}"
    comment: "{{ item.comment }}"
  loop:
    - { port: 22, protocol:  tcp, comment: "SSH" }
    - { port: 80, protocol:  tcp, comment: "HTTP" }
    - { port: 443, protocol:  tcp, comment: "HTTPS" }
    - { port: 6443, protocol:  tcp, comment: "k8s kube-apiserver" }
    - { port: 10250, protocol:  tcp, comment: "k8s kubelet" }
    - { port: 10253, protocol:  tcp, comment: "k8s kube-proxy" }
    - { port: 10257, protocol:  tcp, comment: "k8s kube-controller-manager" }
    - { port: 10259, protocol:  tcp, comment: "k8s kube-scheduler" }
  register: ufw_rules

- name: Enable UFW
  ufw:
    state: enabled
    default: deny
  register: ufw_state

- name: Reload ufw
  ufw:
    state: reloaded
  when: ufw_rules.changed or ufw_state.changed | bool

- name: Reboot
  reboot:
  when: ufw_rules.changed or ufw_state.changed | bool
