---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: gollum
  namespace: services
  labels:
    app.kubernetes.io/name: gollum
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: gollum
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gollum
    spec:
      containers:
        - name: gollum
          image: docker.rcomanne.nl/gollum
          env:
            - name: GIT_URL
              value: 'git@github.com:rcomanne/wiki.git'
          ports:
            - name: web
              containerPort: 4567
      imagePullSecrets:
        - name: private-registry
