---
apiVersion: v1
kind: Service
metadata:
  name: gollum
  namespace: services
  labels:
    app.kubernetes.io/name: gollum
spec:
  ports:
    - protocol: TCP
      name: web
      port: 4567
      targetPort: 4567
  selector:
    app.kubernetes.io/name: gollum